### ISSUE TITLE
The HTTP Delete method is needed to support device hot-removal

### ISSUE THREAD

**Issue by jiangliu** [firecracker-microvm/micro-http#12]
The HTTP Delete method is needed to support device hot-removal by using a restful style API, otherwise we need to use PUT to emulate a DELETE operation.

**Comment by changweige** [comment]
Hello,
Seems that it has been quite a long time since the discussion began.
I am trying to draw your attention back to this discussion to see if we truly need more http methods making the APIs more semantical.
DELETE method and even POST method addition to micro-http won't bring too much burden though micro-http is a minimal
 implementation of http server. With more http methods, we can easily and clearly invoke more operations and services with no need to write complicated http body and emulate various verbs from http.

I am curious if developers of micro-http are strongly objected against adding more http methods? Or do you have any further plan or vision on this but no buffer for this work yet?
